### ISSUE TITLE
Multiple ModuleNotFound Errors 

### ISSUE THREAD

**Issue by master-of-none** [nikhil-ravi/LeetScrape#5]
Can you add the pre-requisites required for the leetscrape, because when I ran this in Virtual Environment, multiple packages are missing. Can you add the packages required in the Readme to run this command ?

**Comment by nikhil-ravi** [comment]
How did you install the package? If you used `pip install leetscrape`, it should already install the dependencies. In any case, the [`pyproject.toml`](https://github.com/nikhil-ravi/LeetScrape/blob/1669a95c901a4df980e96eb8f55c1f0d0c0d8f8a/pyproject.toml#L11-L40) has all the dependencies.

**Comment by master-of-none** [comment]
Thanks, I will check it out
