### ISSUE TITLE
Api request fails

### ISSUE THREAD

**Issue by mickstar** [nikhil-ravi/LeetScrape#8]
Looks like leetcode has changed their API accessbility
the GET to https://leetcode.com/api/problems/all/ fails on my machine (RC 403)
and a quick CURL reveals it's returning a bunch of JS. it seems to render fine on chrome so maybe we need to switch out to
a webdriver instead of HTTP Requests

Anyone know of an easy way to get the GET request working?

**Comment by nikhil-ravi** [comment]
The new commit (80fc2a4) to the main branch should fix this. I tried adding HTTP headers and that worked.
